=== QuasarX1/Phys205Project/simulation/layout_schema/simulation_layout_schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://raw.githubusercontent.com/QuasarX1/Phys205Project/dev/simulation/layout_schema"
    elementFormDefault="qualified"
    xmlns="http://raw.githubusercontent.com/QuasarX1/Phys205Project/dev/simulation/layout_schema"
    xmlns:mstns="http://raw.githubusercontent.com/QuasarX1/Phys205Project/dev/simulation/layout_schema"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">


<!-- Vectors -->
  <xs:complexType name="Vector2">
    <xs:attribute name="x" type="xs:float" default="0.0" />
    <xs:attribute name="y" type="xs:float" default="0.0" />
  </xs:complexType>

  <xs:complexType name="Vector3">
    <xs:attribute name="x" type="xs:float" default="0.0" />
    <xs:attribute name="y" type="xs:float" default="0.0" />
    <xs:attribute name="z" type="xs:float" default="0.0" />
  </xs:complexType>


<!-- Colour -->
  <xs:complexType name="Color">
    <xs:attribute name="r" type="xs:int" default="0" />
    <xs:attribute name="g" type="xs:int" default="0" />
    <xs:attribute name="b" type="xs:int" default="0" />
    <xs:attribute name="a" type="xs:int" default="255" />
  </xs:complexType>


<!-- Free Body -->
  <xs:complexType name="free_body_type">
    <xs:sequence>
      <xs:element name="velocity" type="Vector3" minOccurs="1" maxOccurs="1" />
      <xs:element name="bound_entity_name" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="mass" type="xs:float" use="required" />
    <xs:attribute name="moment_of_inertia" type="xs:float" default="0.0" />
    <xs:attribute name="rotational_period" type="xs:float" default="0.0" />
  </xs:complexType>


<!-- Entities -->
  <xs:complexType name="entity_type">
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>
  
  <xs:complexType name="moveable_type">
    <xs:complexContent>
      <xs:extension base="entity_type">
        <xs:sequence>
          <xs:element name="location" type="Vector3" minOccurs="1" maxOccurs="1" />
          <xs:element name="facing" type="Vector3" minOccurs="1" maxOccurs="1" />
          <xs:element name="vertical" type="Vector3" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="visable" type="xs:boolean" default="true" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>



  <xs:complexType name="renderable_2Dline_type">
    <xs:complexContent>
      <xs:extension base="moveable_type">
        <xs:sequence>
          <xs:element name="point1" type="Vector3" minOccurs="1" maxOccurs="1" />
          <xs:element name="point2" type="Vector3" minOccurs="1" maxOccurs="1" />
          <xs:element name="colour" type="Color" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="length" type="xs:float" default="1.0" />
        <xs:attribute name="point1_is_midpoint" type="xs:boolean" default="false" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  
    
  <xs:complexType name="renderable_simple2Dcircle_type">
    <xs:complexContent>
      <xs:extension base="moveable_type">
        <xs:sequence>
          <xs:element name="colour" type="Color" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="radius" type="xs:float" default="1.0" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  
  
  <xs:complexType name="unitcube_wireframe_type">
    <xs:complexContent>
      <xs:extension base="moveable_type">
        <xs:sequence>
          <xs:element name="colour" type="Color" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="scale" type="xs:float" default="1.0" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  
  
  <xs:complexType name="triangularpyrimid_wireframe_type">
    <xs:complexContent>
      <xs:extension base="moveable_type">
        <xs:sequence>
          <xs:element name="colour" type="Color" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="scale" type="xs:float" default="1.0" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  
  
  
  
  <!--Renderable_Simple2DPolygon-->
  





  <xs:complexType name="sphere_type">
    <xs:complexContent>
      <xs:extension base="moveable_type">
        <xs:sequence>
          <xs:element name="colour" type="Color"  minOccurs="1" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="radius" type="xs:float" default="1.0" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="camera_type">
    <xs:complexContent>
      <xs:extension base="moveable_type">
        <xs:attribute name="name" type="xs:string" fixed="camera" />
        <xs:attribute name="width" type="xs:integer" use="required" />
        <xs:attribute name="height" type="xs:integer" use="required" />
        <xs:attribute name="field_of_vision" type="xs:float" default="0.5" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  
<!-- Leaf Entities -->
  <xs:complexType name="star_type">
    <xs:complexContent>
      <xs:extension base="sphere_type">
        <xs:sequence>
          <xs:element name="free_body" type="free_body_type" minOccurs="1" maxOccurs="1" />
          <xs:element name="colour" type="Color" minOccurs="0" maxOccurs="0" />
        </xs:sequence>
        <xs:attribute name="tempriture" type="xs:float" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  
  
  <xs:complexType name="planet_type">
    <xs:complexContent>
      <xs:extension base="sphere_type">
        <xs:sequence>
          <xs:element name="free_body" type="free_body_type" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="parent_star" type="xs:string" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  
  
  <xs:complexType name="croshair_type">
    <xs:complexContent>
      <xs:extension base="moveable_type">
        <xs:sequence>
          <xs:element name="colour" type="Color" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="scale" type="xs:float" default="0.05" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  
  
  <xs:complexType name="croshair_3D_type">
    <xs:complexContent>
      <xs:extension base="moveable_type">
        <xs:sequence>
          <xs:element name="colour" type="Color" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="scale" type="xs:float" default="0.05" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  

<!-- Entity Groups -->
  <xs:group name="entities_2D_group">
    <xs:choice>
      <xs:element name="renderable_2Dline" type="renderable_2Dline_type" />
      <xs:element name="renderable_simple2Dcircle" type="renderable_simple2Dcircle_type" />
      <xs:element name="croshair" type="croshair_type" />
    </xs:choice>
  </xs:group>
  
  <xs:group name="entities_3D_group">
    <xs:choice>
      <xs:element name="sphere" type="sphere_type" />
      <xs:element name="unitcube_wireframe" type="unitcube_wireframe_type" />
      <xs:element name="triangularpyrimid_wireframe" type="triangularpyrimid_wireframe_type" />
      <xs:element name="croshair_3D" type="croshair_3D_type" />
      <xs:element name="star" type="star_type" />
      <xs:element name="planet" type="planet_type" />
    </xs:choice>
  </xs:group>
  
  <xs:group name="mixed_entities_group">
    <xs:choice>
      <xs:element name="renderable_2Dline" type="renderable_2Dline_type" />
      <xs:element name="renderable_simple2Dcircle" type="renderable_simple2Dcircle_type" />
      <xs:element name="croshair" type="croshair_type" />
      <xs:element name="sphere" type="sphere_type" />
      <xs:element name="unitcube_wireframe" type="unitcube_wireframe_type" />
      <xs:element name="triangularpyrimid_wireframe" type="triangularpyrimid_wireframe_type" />
      <xs:element name="croshair_3D" type="croshair_3D_type" />
      <xs:element name="star" type="star_type" />
      <xs:element name="planet" type="planet_type" />
    </xs:choice>
  </xs:group>
  
  
<!-- Layer Types -->
  <xs:complexType name="layer_2D_type">
    <xs:sequence>
      <xs:group ref="entities_2D_group" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="render_capability" type="xs:boolean" default="true" />
  </xs:complexType>

  <xs:complexType name="layer_3D_type">
    <xs:sequence>
      <xs:group ref="entities_3D_group" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="render_capability" type="xs:boolean" default="true" />
  </xs:complexType>

  <xs:complexType name="mixed_layer_type">
    <xs:sequence>
      <xs:group ref="mixed_entities_group" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="render_capability" type="xs:boolean" default="true" />
  </xs:complexType>

  <xs:group name="layers_group">
    <xs:choice>
      <xs:element name="layer_2D" type="layer_2D_type" />
      <xs:element name="layer_3D" type="layer_3D_type" />
      <xs:element name="mixed_layer" type="mixed_layer_type" />
    </xs:choice>
  </xs:group>

  
  
  <xs:complexType name="simulation_type">
    <xs:sequence>
      <xs:element name="camera" type="camera_type" minOccurs="0" />
      <xs:group ref="layers_group" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="render_capability" type="xs:boolean" default="true" />
  </xs:complexType>

  
  
  <xs:element name="simulation" type="simulation_type" />
  
</xs:schema>

=== QuasarX1/Phys205Project/experements/Solar_System.xml
<?xml version="1.0" encoding="utf-8"?>

<simulation xmlns="http://raw.githubusercontent.com/QuasarX1/Phys205Project/dev/simulation/custom_xml"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://raw.githubusercontent.com/QuasarX1/Phys205Project/dev/simulation/custom_xml simulation_layout_schema.xsd"
            render_capability="false"
            timescale="86400">

  <camera width="500" height="500" field_of_vision="0.5">
    <location x="0" y="0" z="-2000000000" />
    <facing x="0" y="0" z="1" />
    <vertical x="0" y="1" z="0" />
  </camera>

  <layer_3D name="simulation_layer" render_capability="true">
    <star name="sun" tempriture="5700" radius="6051800">
      <location x="0" y="0" z="0" />
      <facing x="1" y="0" z="0" />
      <vertical x="0" y="1" z="0" />
      <free_body mass="1989000000000000000000000000000" rotational_period="790517880">
        <velocity x="0" y="0" z="0" />
      </free_body>
    </star>

    <planet name="mercury" radius="2439000" parent_star="sun">
      <location x="5588000000" y="0" z="0" />
      <facing x="1" y="0" z="0" />
      <vertical x="0" y="1" z="0" />
      <colour r="255" g="150" b="0" a="255" />
      <free_body mass="330100000000000000000000" rotational_period="5067000">
        <velocity x="0" y="0" z="47362" />
      </free_body>
    </planet>

    <planet name="venus" radius="6051000" parent_star="sun">
      <location x="107800000000" y="0" z="0" />
      <facing x="1" y="0" z="0" />
      <vertical x="0" y="1" z="0" />
      <colour r="135" g="206" b="235" a="255" />
      <free_body mass="4868000000000000000000000" rotational_period="10087200">
        <velocity x="0" y="0" z="35020" />
      </free_body>
    </planet>

    <planet name="earth" radius="6371000" parent_star="sun">
      <location x="149600000000" y="0" z="0" />
      <facing x="1" y="0" z="0" />
      <vertical x="0" y="1" z="0" />
      <colour r="0" g="255" b="0" a="255" />
      <free_body mass="5972000000000000000000000" rotational_period="84816">
        <velocity x="0" y="0" z="29979.3018" />
      </free_body>
    </planet>

    <planet name="mars" radius="3389000" parent_star="sun">
      <location x="217900000000" y="0" z="0" />
      <facing x="1" y="0" z="0" />
      <vertical x="0" y="1" z="0" />
      <colour r="255" g="0" b="0" a="255" />
      <free_body mass="5972000000000000000000000" rotational_period="90720">
        <velocity x="0" y="0" z="24070" />
      </free_body>
    </planet>

    <planet name="jupiter" radius="63710000" parent_star="sun">
      <location x="776200000000" y="0" z="0" />
      <facing x="1" y="0" z="0" />
      <vertical x="0" y="1" z="0" />
      <colour r="255" g="75" b="0" a="255" />
      <free_body mass="18980000000000000000000000000" rotational_period="35784">
        <velocity x="0" y="0" z="13070" />
      </free_body>
    </planet>

    <planet name="saturn" radius="58230000" parent_star="sun">
      <location x="1496000000000" y="0" z="0" />
      <facing x="1" y="0" z="0" />
      <vertical x="0" y="1" z="0" />
      <colour r="150" g="150" b="0" a="255" />
      <free_body mass="5.68300000000000000000000000" rotational_period="38484">
        <velocity x="0" y="0" z="9680" />
      </free_body>
    </planet>

    <planet name="uranus" radius="25360000" parent_star="sun">
      <location x="2962000000000" y="0" z="0" />
      <facing x="1" y="0" z="0" />
      <vertical x="0" y="1" z="0" />
      <colour r="184" g="43" b="70" a="255" />
      <free_body mass="86810000000000000000000000" rotational_period="61992">
        <velocity x="0" y="0" z="6800" />
      </free_body>
    </planet>

    <planet name="neptune" radius="24620000" parent_star="sun">
      <location x="4476000000000" y="0" z="0" />
      <facing x="1" y="0" z="0" />
      <vertical x="0" y="1" z="0" />
      <colour r="0" g="0" b="255" a="255" />
      <free_body mass="102400000000000000000000000" rotational_period="57924">
        <velocity x="0" y="0" z="5430" />
      </free_body>
    </planet>

    <planet name="pluto" radius="1188000" parent_star="sun">
      <location x="5906000000000" y="0" z="0" />
      <facing x="1" y="0" z="0" />
      <vertical x="0" y="1" z="0" />
      <colour r="128" g="0" b="128" a="255" />
      <free_body mass="13030000000000000000000" rotational_period="552960">
        <velocity x="0" y="0" z="4743" />
      </free_body>
    </planet>
  </layer_3D>

  <seperation_logger name="interior_plannet_orbit_logger" show_graphs="false" trigger_type="time_period"
                     trigger_limit="31557600" zero_time_on_action="false" file_save_path="./">
    <logged_entity entity_name="mercury" layer_name="simulation_layer" />
    <logged_entity entity_name="venus" layer_name="simulation_layer" />
    <logged_entity entity_name="earth" layer_name="simulation_layer" />
    <logged_entity entity_name="mars" layer_name="simulation_layer" />
    <reference_entity entity_name="sun" layer_name="simulation_layer" />
  </seperation_logger>

  <seperation_logger name="exterior_plannet_orbit_logger" show_graphs="false" trigger_type="time_period"
                     trigger_limit="5207004000" zero_time_on_action="false" file_save_path="./">
    <logged_entity entity_name="jupiter" layer_name="simulation_layer" />
    <logged_entity entity_name="saturn" layer_name="simulation_layer" />
    <logged_entity entity_name="uranus" layer_name="simulation_layer" />
    <logged_entity entity_name="neptune" layer_name="simulation_layer" />
    <logged_entity entity_name="pluto" layer_name="simulation_layer" />
    <reference_entity entity_name="sun" layer_name="simulation_layer" />
  </seperation_logger>
  
</simulation>

=== QuasarX1/Phys205Project/experements/Distant_Binary_Stars.xml
<?xml version="1.0" encoding="utf-8"?>

<simulation xmlns="http://raw.githubusercontent.com/QuasarX1/Phys205Project/dev/simulation/layout_schema"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://raw.githubusercontent.com/QuasarX1/Phys205Project/dev/simulation/layout_schema simulation_layout_schema.xsd"
            render_capability="true">

  <camera width="500" height="500" field_of_vision="0.5">
    <location x="0" y="0" z="-2000000000" />
    <facing x="0" y="0" z="1" />
    <vertical x="0" y="1" z="0" />
  </camera>

  <layer_3D name="simulation_layer" render_capability="true">
    <star name="sun" tempriture="5700" radius="6051800">
      <location x="149600000000" y="0" z="0" />
      <facing x="1" y="0" z="0" />
      <vertical x="0" y="1" z="0" />
      <free_body mass="1989000000000000000000000000000" rotational_period="790517880">
        <velocity x="0" y="0" z="0" />
      </free_body>
    </star>

    <star name="CygnusX1" tempriture="31000" radius="14622300000">
      <location x="57710000000000000000" y="0" z="0" />
      <facing x="1" y="0" z="0" />
      <vertical x="0" y="1" z="0" />
      <free_body mass="30000000000000000000000000000000" rotational_period="483840">
        <velocity x="0" y="0" z="-13000" />
      </free_body>
    </star>

    <star name="SiriusA" tempriture="9940" radius="1191369300">
      <location x="81551000000000000" y="0" z="0" />
      <facing x="1" y="0" z="0" />
      <vertical x="0" y="1" z="0" />
      <free_body mass="2022000000000000000000000000000" rotational_period="475200">
        <velocity x="0" y="0" z="-5500" />
      </free_body>
    </star>

    <planet name="earth" radius="6371000" parent_star="sun">
      <location x="149600000000" y="0" z="0" />
      <facing x="1" y="0" z="0" />
      <vertical x="0" y="1" z="0" />
      <colour r="0" g="255" b="0" a="0" />
      <free_body mass="5972000000000000000000000" rotational_period="84816">
        <velocity x="0" y="0" z="29979.3018" />
      </free_body>
    </planet>
  </layer_3D>
  
</simulation>
